config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    delete "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
      put :block
    end
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new], only: [:new, :create, :update, :edit]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.order('created_at desc').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = current_user.statuses.new
    @status.build_document

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])
    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    @document = @status.document
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
    end
    respond_to do |format|
      if @status.update_attributes(params[:status]) &&
         @document && @document.update_attributes(params[:status][:document_attributes])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
   @status = current_user.statuses.find(params[:id])
   @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.input :content, :label => "title", input_html: { rows: 1, class: "input", :maxlength=>"49" } %>
  <%= f.input :content, :label => "entry", input_html: { rows: 4, class: 'input-xxlarge' } %>


  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
    <%= link_to "Back", statuses_path, class: 'btn' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<%= page_header do %>
  <h1>Edit Status</h1>
<% end %>

<%= render 'form' %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All of the Statuses</h1>
</div>

      <% @statuses.each do |status| %>
        <% if can_display_status?(status) %>
        <div class="media-body">
          <h6 class="media-heading"><%= status.user.full_name %></h6>
            <div class="status media">
              <%= avatar_profile_link status.user, {}, class: 'pull-right' %>
              <p><%= status.title %></p>
              <p><%= status.content %></p>
              <%= status_document_link(status) %>
              <div class="meta">
                  <%= link_to time_ago_in_words(status.created_at) + " ago", status %> 
                  <% if signed_in? && current_user == status.user %>
                  <span class="admin">
                    | <%= link_to "Edit", edit_status_path(status) %> | 
                    <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %>
                  </span>
                  <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/statuses/new.html.erb
<%= page_header do %>
  <h3>add a new entry</h3>
<% end %>

<%= render 'form' %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span8 offset2">
    <%= page_header do %>
      <h1>
        <%= avatar_profile_link @status.user %>
        <%= @status.user.full_name %>
        <small><%= time_ago_in_words(@status.created_at) + " ago" %></small>
      </h1>
    <% end %>

    
    <p>
      <%= @status.content %>
    </p>


    <hr />

    <% if @status.document && @status.document.attachment? %>
      <%= status_document_link @status %>
      <hr />
    <% end %>

    <div class="meta">
      <%= link_to 'Back', statuses_path %>
      <% if signed_in? && @status.user == current_user %>
        |
        <%= link_to "Edit", edit_status_path(@status) %> | 
        <%= link_to "Delete", @status, method: :delete, data: { confirm: "Are you sure your want to delete this status?"} %>
      <% end %>
    </div>
  </div>
</div>